#!/usr/bin/zsh

if [[ -z $DOTFILES ]]; then
	DOTFILES=$HOME/.dotfiles
fi

if [[ -z $STOW_FOLDERS ]]; then
	STOW_FOLDERS=tmux,zsh
fi

pushd $DOTFILES
pwd

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	echo "stow $folder"
	stow -D $folder
	stow $folder
done

popd
echo "Done with stow"

